# docker-compose -f infra-on-docker.yml up -d --build
# docker-compose -f infra-on-docker.yml down --remove-orphans

version: '3.7'

services:

  crud-db:
    image: postgres:14.2-alpine
    hostname: crud
    container_name: crud
    restart: always
    networks:
      - crud-net
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_MULTIPLE_DATABASES: '"crud"'
    ports:
      - 5432:5432
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

  pgAdmin:
    image: dpage/pgadmin4:6.14
    hostname: crud-pgAdminhn
    container_name: crud-pgAdmincn
    restart: always
    networks:
      - crud-net
    depends_on:
      - crud-db
    environment:
      PGADMIN_DEFAULT_EMAIL: user@crud.com
      PGADMIN_DEFAULT_PASSWORD: pass
      PGADMIN_DISABLE_POSTFIX: "true"
    ports:
      - 9046:80
      - 9047:443

  sonarqube:
    image: sonarqube:10.0.0-community
    hostname: sonarqube
    container_name: sonarqube
    restart: 'unless-stopped'
    depends_on:
      - crud-db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://crud-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9044:9000"

networks:
  crud-net:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data: